
```{r setup, include=FALSE}
# Load libraries.  Install if not already installed.
list.packages <- c("plyr","dplyr","data.table","sqldf","reticulate","visNetwork")
new.packages <- list.packages[!(list.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
lapply(list.packages, require, character.only = T)
```

```{r}
# https://www.infoworld.com/article/3340120/how-to-run-python-in-r.html
# Using R Markdown to write R code and Python code (and cypher in this case) all in the same file!
```

```{r}
# install Python packages
virtualenv_install(envname = "my_new_env",c("neo4j","pandas"))
# use_virtualenv("/Cloud/project/my_new_env", required = TRUE)
py_run_string("from neo4j import GraphDatabase")
py_run_string("import pandas as pd")
```

```{python}
# Load a graph dataset into Neo4j
# Thank you to @seankrobinson for the Python load demo
import pandas as pd
from neo4j import GraphDatabase

URI      = "<URI>"
creds    = ('neo4j', '<pwd>')
driver   = GraphDatabase.driver(URI, auth=creds)

drop = False # Drop existing graphs/models if already in memory

def run_cypher(cypher, results=False):
    with driver.session() as session:
        r = session.run(cypher).data()
    if results:
        return r
      
pd.read_csv('https://raw.githubusercontent.com/seankrobinson/Protein-Interaction_Link-Prediction/master/PP-Pathways_ppi.csv',
             header=None).head()

c = '''
// Create constraints
CREATE CONSTRAINT proteins IF NOT EXISTS ON (p:Protein) ASSERT p.id IS UNIQUE;
'''
run_cypher(c)             



# Create Nodes
for i in [0,1]:
    c = '''
    // Load node list
    LOAD CSV FROM 'https://raw.githubusercontent.com/seankrobinson/Protein-Interaction_Link-Prediction/master/PP-Pathways_ppi.csv' AS line
    WITH line
    MERGE (p:Protein {{id: line[{index}]}})
    RETURN COUNT(DISTINCT p)
    '''
    result = run_cypher(c.format(index=i), results=True)
    print(result)
    
# Create Edges    
c = '''
// Load node list
LOAD CSV FROM 'https://raw.githubusercontent.com/seankrobinson/Protein-Interaction_Link-Prediction/master/PP-Pathways_ppi.csv' AS line
WITH line
MATCH (p1:Protein {id: line[0]})
WITH line, p1
MATCH (p2:Protein {id: line[1]})
MERGE (p1)-[r:INTERACTS_WITH]->(p2)
RETURN COUNT(r)
'''
result = run_cypher(c, results=True)
print(result)    
```

```{python}
# Run a cypher query and return as Python dataframe
c = '''
match (a:Protein)-[r:INTERACTS_WITH]->(b:Protein)
return a.id as src_id, type(r) as relationship_type, b.id as tgt_id
limit 25
'''
result = run_cypher(c, results=True)
df = pd.DataFrame([dict(record) for record in result])
print(df.head())
```

```{r}
# Convert to R dataframe
df <- py$df
head(df)
```

```{r}
# Prep Data
e = df %>% select(from = src_id, to = tgt_id, label = relationship_type)
n = sqldf('
                select distinct id 
                from (
                  select distinct "from" as id
                  from e
                  
                  union
                  
                  select distinct "to" as id
                  from e
                ) a')
n$group = "group"
head(n)
head(e)
```

```{r}
# Visualize Network
visNetwork(
  # height = 900, width = 900, background = "#f8f8ff",
  n, # nodes
  e  # edges
) %>%
  # visLegend() %>%
  visGroups(groupname = "group", shape = "icon", icon = list(code = "f275", size = 75, color = "blue")) %>%
  visNodes(mass = 12, physics = T) %>%
    visLayout(randomSeed = 12345) %>%
    visInteraction(multiselect = T) %>%
    visOptions(selectedBy = "label",
               highlightNearest = T,
               nodesIdSelection = T) %>%
    visEdges(shadow = F,
             smooth = F,
             arrows = list(to = list(enabled = T, scaleFactor = 2)),
             color = list(color = "lightblue", highlight = "red")) %>%
    visPhysics(stabilization = TRUE, enabled = TRUE) %>%
    visOptions(manipulation = T) %>%
    addFontAwesome(name = "font-awesome-visNetwork")
```


```{r}
# Visualize Network
visNetwork(
  n, 
  e
) %>%
  visPhysics(stabilization = TRUE, enabled = TRUE) %>%
  visOptions(highlightNearest = list(enabled = T, degree = 1, hover = F), autoResize = TRUE, collapse = FALSE) %>%
  visEdges(color = list(highlight = "red")) %>% # The colour of the edge linking nodes
  visLayout(improvedLayout = TRUE) %>%
  # visEdges(arrows = edges$arrows) %>%
  visInteraction(multiselect = F)
```

